import"./assets/modulepreload-polyfill-B5Qt9EMX.js";function u(t){document.querySelectorAll(".section").forEach(c=>{c.classList.remove("active")});const o=document.getElementById(t);o&&(o.classList.add("active"),window.scrollTo({top:0,behavior:"smooth"}));const i=document.querySelectorAll(".nav-link");i.forEach(c=>{c.classList.remove("active")});const d=Array.from(i).find(c=>c.getAttribute("href")==="#"+t);d&&d.classList.add("active")}function p(){const t=document.getElementById("introduction");t&&t.classList.add("active");const e=document.querySelector(".nav-link");e&&e.classList.add("active"),document.querySelectorAll(".nav-link").forEach(n=>{n.addEventListener("click",s=>{s.preventDefault();const a=s.target.getAttribute("href").substring(1);u(a)})}),document.querySelectorAll(".component-item[data-component]").forEach(n=>{n.addEventListener("click",()=>{const s=n.getAttribute("data-title"),a=n.getAttribute("data-description");m(s,a)})}),document.querySelectorAll(".service-item[data-service]").forEach(n=>{n.addEventListener("click",()=>{const s=n.getAttribute("data-title"),a=n.getAttribute("data-description");m(s,a)})});const c=document.querySelector(".close-modal");c&&c.addEventListener("click",()=>{l()});const r=document.getElementById("infoModal");r&&r.addEventListener("click",n=>{n.target===r&&l()}),document.addEventListener("keydown",n=>{n.key==="Escape"&&l()}),document.querySelectorAll("pre code").forEach(n=>{n.addEventListener("click",function(){const s=document.createRange();s.selectNodeContents(this);const a=window.getSelection();a.removeAllRanges(),a.addRange(s)})}),f()}function m(t,e){const o=document.getElementById("infoModal"),i=document.getElementById("modalBody");o&&i&&(i.innerHTML=`<h3>${t}</h3><p>${e}</p>`,o.classList.add("show"))}function l(){const t=document.getElementById("infoModal");t&&t.classList.remove("show")}function f(){const t={threshold:.1,rootMargin:"0px 0px -50px 0px"},e=new IntersectionObserver(o=>{o.forEach(i=>{i.isIntersecting&&(i.target.style.opacity="1",i.target.style.transform="translateY(0)")})},t);document.querySelectorAll(".feature-card, .component-item, .service-item, .intro-box, .tech-stack, .info-box").forEach(o=>{o.style.opacity="0.7",o.style.transform="translateY(10px)",o.style.transition="opacity 0.5s ease, transform 0.5s ease",e.observe(o)})}function v(){document.querySelectorAll("pre").forEach(t=>{const e=document.createElement("button");e.textContent="📋 Kopiuj",e.className="copy-button",e.style.cssText=`
            position: absolute;
            top: 8px;
            right: 8px;
            background-color: var(--primary-green);
            color: white;
            border: none;
            border-radius: 4px;
            padding: 6px 12px;
            font-size: 12px;
            cursor: pointer;
            opacity: 0;
            transition: opacity 0.2s;
        `,t.style.position="relative",t.appendChild(e),t.addEventListener("mouseenter",()=>{e.style.opacity="1"}),t.addEventListener("mouseleave",()=>{e.style.opacity="0"}),e.addEventListener("click",()=>{const o=t.textContent;navigator.clipboard.writeText(o).then(()=>{const i=e.textContent;e.textContent="✅ Skopiowano!",setTimeout(()=>{e.textContent=i},2e3)})})})}document.addEventListener("DOMContentLoaded",()=>{p(),v();const t=window.location.hash.substring(1);t&&u(t)});window.addEventListener("hashchange",()=>{const t=window.location.hash.substring(1);t&&u(t)});window.addEventListener("resize",()=>{});
